print("http://dxprit-saleh-king99-55-39-hackers.phpnet.us/sex.admins.rubika.html")
print("http://dxprit-filtering-rubika-sxs.gigfa.com/dxprit.html")
print("http://dscript-hazrat-285-92-pantrex-hacker-yftt15l.gigfa.com/sex.admins.rubika.html")
print("dxprit.purnhub")
print("DXPRIT.SEXE.PURNHUB")
